name: Instrumented Android Tests
on: pull_request

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: set up JDK 17
        - uses: actions/setup-java@v2
          - with:
            java-version: '17'
            distribution: 'adopt'

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck