name: CI
on: [ pull_request ]

env:
  JAVA_VERSION: 18
  JAVA_DIST: adopt

jobs:
  ui-tests:
    name: Run UI Tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: ${{ env.JAVA_DIST }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Build app
        run: ./gradlew assembleDebug assembleAndroidTest

      # Used in debugging the workflow
      - name: List files in directory
        run: ls -R app/build/outputs/apk/

      - name: Run tests
        uses: emulator-wtf/run-tests@v0.9.9
        with:
          api-token: ${{ secrets.EW_API_TOKEN }}
          app: app/build/outputs/apk/debug/app-debug.apk
          test: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
          outputs-dir: build/test-results
      - name: Publish test report
        uses: mikepenz/action-junit-report@v2
        if: always() # always run even if the tests fail
        with:
          report_paths: 'build/test-results/**/*.xml'

  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: ${{ env.JAVA_DIST }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Run All Unit Tests
        run: ./gradlew test --info
